version: '3.8'

services:

  shomei_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shomei_backend
    ports:
      - "127.0.0.1:3371:3371"
      - "127.0.0.1:4983:4983"
    environment:
      - NODE_ENV=production
      - PORT=3371
    networks:
        - infra-network
        - shomei-network
    env_file:
      - .env
    restart: unless-stopped

  shomei_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:3371}
    container_name: shomei_frontend
    networks:
        - shomei-network
    ports:
      - "127.0.0.1:3000:80"
    restart: unless-stopped

networks:
  infra-network:
    external: true
  shomei-network:
    external: true
